on:
  push:
    branches:
      - master

jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: Check PR labels action step
      id: check_pr_labels
      uses: nxtstep/check-pr-labels-on-push-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: '["enhancement"]'
    - name: See result
      run: echo "${{ steps.check_pr_labels.outputs.result }}"
    - name: Matching labels
      run: echo "${{ steps.check_pr_labels.outputs.matchedLabels }}"
    - name: All labels
      run: echo "${{ steps.check_pr_labels.outputs.allLabels }}"
